#Notification settings (please note: any "command" could have 'exit 1', make sure the notification will have appropriate details about failure)
notifications:
  email:
    recipients: "my@box.com"
    on_start: "never"
    on_failure: "always"
    on_success: "always"
#Build configuration
build:
  projectFolder:  'project'
  buildCommand: "mvn clean test"
#Database configuration
database:
  databaseFolder: 'database'
  databaseCommand: "mvn clean test -Dscope=FlywayMigration"
#Deploy configuration
deploy:
  deployCommand: "mvn clean install"
#Test configuration (should be run in parallel)
test:
- testFolder: "test"
  name: "performance"
  testCommand: "date +"%T.%3N"
- testFolder: "test"
  name: "regression"
  testCommand: "date +"%T.%3N"
- testFolder: "test"
  name: "integration"
  testCommand: "date +"%T.%3N"
