apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ BRANCH_NAME }}-httpd-deployment
  labels:
    app: {{ BRANCH_NAME }}-httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ BRANCH_NAME }}-httpd
  template:
    metadata:
      labels:
        app: {{ BRANCH_NAME }}-httpd
    spec:
      containers:
      - name: {{ BRANCH_NAME }}-httpd
        image: mkgeka/kuber-lamp-7:{{ BUILD_ID }}
        ports:
        - containerPort: 80
      imagePullPolicy: Always
