---
# tasks file for playbook1
- name: Deploy the ingress-controller
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/nginx-controller.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the nginx application
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/nginx-deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
   wait: yes
   wait_condition:
    reason: 'NewReplicaSetAvailable'
    status: 'True'
    type: 'Progressing'
  ignore_errors: yes

- name: Deploy the httpd application
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/httpd-deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
   wait: yes
   wait_condition:
    reason: 'NewReplicaSetAvailable'
    status: 'True'
    type: 'Progressing'
  ignore_errors: yes

- name: Deploy the ingress
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/ingress.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

