---
# tasks file for playbook1
- name: Deploy the service
  k8s:
   state: present
   definition: ""
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the application
  k8s:
   state: present
   definition: ""
   validate_certs: no
   namespace: default
  ignore_errors: yes
