---
# tasks file for playbook1
- name: Build an image and push it to a private repo
  tags: build
  community.general.docker_image:
    build:
      path: ../../../../docker 
    name: mkgeka/kuber-lamp-7
    tag: v1
    push: yes
    source: build

- name: Deploy the service
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the application
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: wait
  tags: wait
  shell: sleep 100
  args:
    executable: /bin/bash


- name: Deploy the service
  tags: k8s
  k8s:
   state: absent
   definition: "{{ lookup('file', '../../../../k8s/deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the application
  tags: k8s
  k8s:
   state: absent
   definition: "{{ lookup('file', '../../../../k8s/service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

