---
# tasks file for playbook1
- name: Deploy the service
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the application
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: wait
  tags: k8s
  shell: sleep 300
  args:
    executable: /bin/bash


- name: Deploy the service
  tags: k8s
  k8s:
   state: absent
   definition: "{{ lookup('file', '../../../../k8s/deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the application
  tags: k8s
  k8s:
   state: absent
   definition: "{{ lookup('file', '../../../../k8s/service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

