---
# tasks file for playbook1
- name: Create a data container {{ BRANCH_NAME }}
  tags: testingimage
  community.general.docker_container:
    name: 'TEST-{{ BRANCH_NAME }}'
    image: 'mkgeka/kuber-lamp-7:{{ BUILD_ID }}'
    ports:
      - "127.0.0.1:36893:80" 

- name: Testing the image before deploying
  tags: testingimage
  wait_for: 
    port: 36893
    delay: 5

- name: Delete a data container {{ BRANCH_NAME }}
  tags: testingimage
  community.general.docker_container:
    name: 'TEST-{{ BRANCH_NAME }}'
    state: absent

- name: Creating the nginx application file with  "{{ BUILD_ID }}"
  tags: build,update
  template:
   src: nginx-deployment.yml
   dest: /tmp/{{ BRANCH_NAME }}-nginx-{{ BUILD_ID }}.yml
   owner: root
   group: root
   mode: 0644

- name: Testing the nginx application file/ before deploying
  tags: build,update
  wait_for: 
    path: /tmp/{{ BRANCH_NAME }}-nginx-{{ BUILD_ID }}.yml

- name: Deploy the nginx application
  tags: build,update
  k8s:
   state: present
   src: /tmp/{{ BRANCH_NAME }}-nginx-{{ BUILD_ID }}.yml
   validate_certs: no
   namespace: default
   wait: yes
   wait_condition:
    reason: 'NewReplicaSetAvailable'
    status: 'True'
    type: 'Progressing'
  ignore_errors: yes

- name: Deploy the nginx-service.yml
  tags: build
  k8s:
   state: present
   definition: "{{ lookup('file', '../templates/nginx-service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Creating the "{{ BRANCH_NAME }}" application file with  "{{ BUILD_ID }}"
  tags: build,update
  template:
   src: httpd-deployment.yml
   dest: /tmp/{{ BRANCH_NAME }}-httpd-{{ BUILD_ID }}.yml
   owner: root
   group: root
   mode: 0644

- name: Testing the "{{ BRANCH_NAME }}" application file/ before deploying
  tags: build,update
  wait_for: 
    path: /tmp/{{ BRANCH_NAME }}-httpd-{{ BUILD_ID }}.yml

- name: Deploy the "{{ BRANCH_NAME }}" application
  tags: build,update
  k8s:
   state: present
   src: /tmp/{{ BRANCH_NAME }}-httpd-{{ BUILD_ID }}.yml
   validate_certs: no
   namespace: default
   wait: yes
   wait_condition:
    reason: 'NewReplicaSetAvailable'
    status: 'True'
    type: 'Progressing'
  ignore_errors: yes

- name: Creating the "{{ BRANCH_NAME }}" service application file with  "{{ BUILD_ID }}"
  tags: build,update
  template:
   src: httpd-service.yml
   dest:  /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-httpd-service.yml
   owner: root
   group: root
   mode: 0644

- name: Testing the "{{ BRANCH_NAME }}" service application file/ before deploying
  tags: build,update
  wait_for: 
    path: /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-httpd-service.yml

- name: Deploy the "{{ BRANCH_NAME }}" httpd-service
  tags: build
  k8s:
   state: present
   src: /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-httpd-service.yml
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Creating the "{{ BRANCH_NAME }}" ingress file with  "{{ BUILD_ID }}"
  tags: build
  template:
   src: ingress.yml
   dest:  /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-ingress.yml
   owner: root
   group: root
   mode: 0644

- name: Testing the ingress file/ before deploying
  tags: build
  wait_for: 
    path: /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-ingress.yml

- name: Deploy the ingress
  tags: build
  k8s:
   state: present
   src: /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-ingress.yml
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the ingress-controller
  tags: build,ingress-controller
  k8s:
   state: present
   definition: "{{ lookup('file', '../templates/nginx-controller-{{ item }}.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  with_items:
   - [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  ignore_errors: yes

- name: Deleting the httpd application file with  "{{ BUILD_ID }}"
  tags: build,update
  file:
   path: /tmp/{{ BRANCH_NAME }}-httpd-{{ BUILD_ID }}.yml
   state: absent

- name: Deleting the nginx application file with  "{{ BUILD_ID }}"
  tags: build,update
  file:
   path: /tmp/{{ BRANCH_NAME }}-nginx-{{ BUILD_ID }}.yml
   state: absent

- name: Deleting the service  application file with  "{{ BUILD_ID }}"
  tags: build,update
  file:
   path: /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-httpd-service.yml
   state: absent

- name: Deleting the ingress service file with  "{{ BUILD_ID }}"
  tags: build
  file:
   path: /tmp/{{ BRANCH_NAME }}-{{ BUILD_ID }}-ingress.yml
   state: absent

