---
# tasks file for playbook1
- name: Deploy the ingress-controller
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/nginx-controller-{{ item }}.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  with_items:
   - [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  ignore_errors: yes

- name: Deploy the nginx application
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/nginx-deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
   wait: yes
   wait_condition:
    reason: 'NewReplicaSetAvailable'
    status: 'True'
    type: 'Progressing'
  ignore_errors: yes

- name: Deploy the nginx-service.yml
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/nginx-service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the httpd application
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/httpd-deployment.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
   wait: yes
   wait_condition:
    reason: 'NewReplicaSetAvailable'
    status: 'True'
    type: 'Progressing'
  ignore_errors: yes

- name: Deploy the httpd-service
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/httpd-service.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

- name: Deploy the ingress
  tags: k8s
  k8s:
   state: present
   definition: "{{ lookup('file', '../../../../k8s/ingress.yml') | from_yaml }}"
   validate_certs: no
   namespace: default
  ignore_errors: yes

