apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: mkgeka/kuber-lamp-7:${BUILD_ID}
        ports:
        - containerPort: 80
      imagePullPolicy: Always
