---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: http
      port: 80
      targetPort: 80
      NodePort: 30081
  type: LoadBalancer

